myRDB_Project/myRDB_Project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from myRDB_app import views

from . import settings

'''
    sets REST-API urls
'''
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, 'user')
router.register(r'roles', views.RoleViewSet, 'role')
router.register(r'afs', views.AFViewSet, 'af')
router.register(r'gfs', views.GFViewSet, 'gf')
router.register(r'tfs', views.TFViewSet, 'tf')
router.register(r'orgas', views.OrgaViewSet, 'orga')
router.register(r'groups', views.GroupViewSet, 'group')
router.register(r'departments', views.DepartmentViewSet, ' department')
router.register(r'zi_organisations', views.ZI_OrganisationViewSet, 'zi_organisation')
router.register(r'tf_applications', views.TF_ApplicationViewSet, 'tf_application')
router.register(r'usermodelrights', views.UserModelRightsViewSet, 'usermodelrights')
router.register(r'userlistings', views.UserListingViewSet, 'userlisting')
router.register(r'searchlistings', views.CompleteUserListingViewSet, 'searchlisting')
router.register(r'changerequests', views.ChangeRequestsViewSet, 'changerequests')

urlpatterns = [
    url(r'^', include(router.urls)),
    path('', include('django.contrib.auth.urls')),
    path('myRDB/', include('myRDB_app.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myRDB_Project/myRDB_app/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required,permission_required

from . import views

app_name = 'myRDB'
'''
    sets App urls
'''
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_reset/', views.Password_Reset.as_view(), name='password_reset'),
    path('register/', views.Register.as_view(), name='register'),
    path('profile/', login_required(views.Profile.as_view()), name='profile'),
    path('profile/rights_analysis', login_required(views.ProfileRightsAnalysis.as_view()), name='profile_rights_analysis'),
    path('profile/compare/', login_required(views.Compare.as_view()), name='compare'),
    path('csvToMongo/', permission_required('user.is_staff')(views.CSVtoMongoDB.as_view()), name='csvToMongo'),
    path('users/', permission_required('user.is_staff')(views.Users.as_view()), name='users'),
    path('search_all/', permission_required('user.is_staff')(views.Search_All.as_view()), name='search_all'),
    path('request_pool/', permission_required('user.is_staff')(views.RequestPool.as_view()), name='request_pool'),
    path('my_requests/', login_required(views.MyRequests.as_view()), name='my_requests'),
    path('profile/compare/apply_changes/', login_required(views.RightApplication.as_view()), name='apply_changes'),
]

myRDB_Project/myRDB_app/views.py
import csv
import json
import re

import requests
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import datetime

from django.http import HttpResponseRedirect
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .forms import CustomUserCreationForm, SomeForm, ApplyRightForm, DeleteRightForm, AcceptChangeForm, \
    DeclineChangeForm, CustomAuthenticationForm, ProfileHeaderForm
from .models import Role, AF, GF, TF, Orga, Group, Department, ZI_Organisation, TF_Application, User_AF, User_TF, \
    User_GF, ChangeRequests
from rest_framework import viewsets, status
from .serializers import UserSerializer, RoleSerializer, AFSerializer, GFSerializer, TFSerializer, OrgaSerializer, \
    GroupSerializer, DepartmentSerializer, ZI_OrganisationSerializer, TF_ApplicationSerializer, UserListingSerializer, \
    CompleteUserListingSerializer, UserModelRightsSerializer, ChangeRequestsSerializer
from django.views import generic

from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordResetDoneView

User = get_user_model()
docker_container_ip = "http://148.100.245.159:8000"
#proxies = {'http':"http://172.17.0.3:8000"}
#docker_container_ip = "http://0.0.0.0:8000"
#docker_container_ip = "http://127.0.0.1:8000"


class CSVtoMongoDB(generic.FormView):
    '''
        dataimport-view: reads IIQ-csv (currently hardcoded) line by line and populates Database
            1 line equals 1 user-right
            creates user-profiles to be available for activation by signing-up user
            if element deosnt exist -> create and add reference to user model
            else add reference to user model
    '''
    template_name = 'myRDB/csvToMongo.html'
    form_class = SomeForm
    success_url = '#'

    def form_valid(self, form):
        self.start_import_action()
        return super().form_valid(form)

    def start_import_action(self):
        firstline = True
        # TODO: dateiimportfield und pfad müssen noch verbunden werden!
        #
        with open("myRDB_app/static/myRDB/data/Aus IIQ - User und TF komplett Neu_20180817_abMe.csv",
                  encoding='utf-8') as csvfile:
            csvreader = csv.reader(csvfile, delimiter=';', quotechar='"')
            cur_val = 0
            for line in csvreader:
                line = [re.sub(r'\s+', '', e) for e in line]

                if firstline == True:
                    firstline = False
                    pass
                else:
                    print(line)
                    orga = None
                    try:
                        orga = Orga.objects.get(team=line[8])
                    except(KeyError, Orga.DoesNotExist):
                        orga = Orga(team=line[8])
                    orga.save()

                    tf_application = None
                    try:
                        tf_application = TF_Application.objects.get(application_name=line[9])
                    except(KeyError, TF_Application.DoesNotExist):
                        right_color = "hsl(%d, 50%%, 50%%)" % cur_val
                        tf_application = TF_Application(application_name=line[9], color=right_color)
                        cur_val = (cur_val + 20) % 355

                    tf_application.save()

                    tf = None
                    try:
                        tf = TF.objects.get(tf_name=line[3])
                    except(KeyError, TF.DoesNotExist):
                        tf = TF(tf_name=line[3], tf_description=line[4], highest_criticality_in_AF=line[7],
                                tf_owner_orga=orga, tf_application=tf_application, criticality=line[10])
                    tf.save()

                    gf = None
                    try:
                        gf = GF.objects.get(gf_name=line[11])
                    except(KeyError, GF.DoesNotExist):
                        gf = GF(gf_name=line[11], gf_description=line[12])
                        gf.save()
                    gf.tfs.add(tf)
                    gf.save()

                    af = None
                    try:
                        af = AF.objects.get(af_name=line[5])
                    except(KeyError, AF.DoesNotExist):
                        af = AF(af_name=line[5], af_description=line[6])

                    af.save()
                    af.gfs.add(gf)

                    user = None
                    try:
                        user = User.objects.get(identity=line[0])
                        if user.name != line[1]:
                            user.name = line[1]
                        if user.first_name != line[2]:
                            user.first_name = line[2]
                        if user.username != line[0]:
                            user.username = line[0]
                    except(KeyError, User.DoesNotExist):
                        user = User(identity=line[0], name=line[1], first_name=line[2], username=line[0])
                        if not user.orga:
                            user.orga = Orga()
                        if not user.group:
                            user.group = Group()
                        if not user.department:
                            user.department = Department()
                        if not user.zi_organisation:
                            user.zi_organisation = ZI_Organisation()
                        if not user.roles:
                            user.roles = [Role()]
                        if not user.direct_connect_afs:
                            user.direct_connect_afs = [AF()]
                        if not user.direct_connect_gfs:
                            user.direct_connect_gfs = [GF()]
                        if not user.direct_connect_tfs:
                            user.direct_connect_tfs = [TF()]
                        if not user.my_requests:
                            user.my_requests = [ChangeRequests()]
                        if not user.user_afs:
                            user.user_afs = []
                        if not user.transfer_list:
                            user.transfer_list = []
                        if not user.delete_list:
                            user.delete_list = []
                    if user.user_afs.__len__() == 0:
                        user_tf = User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk, color=tf_application.color)
                        user_gf = User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk, tfs=[])
                        user_af = self.create_user_af(line, af)
                        user_gf.tfs.append(user_tf)
                        user_af.gfs.append(user_gf)
                        user.user_afs.append(user_af)
                    else:
                        afcount = 0
                        for uaf in user.user_afs:
                            if uaf.af_name != af.af_name:
                                afcount += 1
                            else:
                                gfcount = 0
                                for ugf in uaf.gfs:
                                    if ugf.gf_name != gf.gf_name:
                                        gfcount += 1
                                    else:
                                        tfcount = 0
                                        for utf in ugf.tfs:
                                            if utf.tf_name != tf.tf_name:
                                                tfcount += 1
                                            else:
                                                break
                                        if tfcount == ugf.tfs.__len__():
                                            ugf.tfs.append(User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                   color=tf_application.color))
                                if gfcount == uaf.gfs.__len__():
                                    uaf.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                           tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                        color=tf_application.color)]))
                        if afcount == user.user_afs.__len__():
                            user_af = self.create_user_af(line, af)
                            user_af.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                       tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                    color=tf_application.color)]))
                            user.user_afs.append(user_af)

                    user.direct_connect_afs.add(af)
                    user.save()

    def create_user_af(self, line, af):
        if line[15] == "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[])
        if line[15] != "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()
                              , af_valid_till=datetime.datetime.strptime(line[16], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] != "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()

myRDB_Project/myRDB_app/templates/myRDB/compare/compare.html
{% extends 'myRDB/base.html' %}
{% block content %}
    {% load asjson %}
    <script type="text/javascript">
        var compare_jsondata = {{ compareUser_graph_data | asjson }};
        var jsondata = {{ jsondata | asjson }};
        var current_site = "{{ current_site }}";
        var compare_user = "{{ compareUser.identity }}";
        var user = "{{ identity_param }}";
        var user_table_data = "{{ table_data }}";
        var transferlistdata = {{ transferlist | asjson }};
        var trashlistdata = {{ deletelist | asjson }};
        var compare_user_table_data = "{{ compareUser_table_data }}";
        var transfer_list_table_data = "{{ transfer_list_table_data }}";
    </script>
<div class="row top-buffer">
    <div class="col-6" id="user_card">
        {% include 'myRDB/profile/profile_head.html' %}
        <div class="card top-buffer">
            {% if view_mode == "Graphische Ansicht" %}
                {% include 'myRDB/circlePackingTemplate.html' %}
            {% else %}
                {% include 'myRDB/profile/profileTableTemplate.html' %}
            {% endif %}
        </div>
    </div>
    <div class="col-6">
        {% include 'myRDB/compare/compare_profile_head.html' %}
        <div class="card top-buffer">
            {% if view_mode == "Graphische Ansicht" %}
                {% include 'myRDB/compare/compareCirclePackingTemplate.html' %}
            {% else %}
                {% include 'myRDB/compare/compareTableTemplate.html' %}
            {% endif %}
        </div>
    </div>
</div>
<div class="row-fluid top-buffer">
    {# hier umschalt button auf tabellarische/visuelle ansicht #}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-2">
                    <label for="viewMode">Ansicht: </label>
                </div>
                <div class="col-3">
                    <form>
                        {% csrf_token %}
                        <input name="user_identity" type="hidden" value="{{ user_identity }}">
                        <input name="user_search" type="hidden" value="{{ compareUser.identity }}">
                        <select id="viewMode" name="view_mode" class="form-control" onchange="form.submit()">
                            {% if view_mode == "Graphische Ansicht"%}
                                <option selected>Graphische Ansicht</option>
                                <option>Tabellarische Ansicht</option>
                            {% else %}
                                <option>Graphische Ansicht</option>
                                <option selected>Tabellarische Ansicht</option>
                            {% endif %}
                        </select>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'myRDB/compare/compare_footer_row.html' %}

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/compare/compareCirclePackingTemplate.html
{% load static %}
{% load asjson %}
{# Hier die Circle-Packing-Visualisierung #}
<div class="card-header">
    <h5>Vergleichsgraph</h5>
</div>
<div class="card-body">
    <script type="text/javascript">
        var compare_user_pk = "{{ compare_user_pk }}";
        var CSRF_TOKEN = "{{ csrf_token }}";
        var updateCompareCP;
    </script>
    <svg id="compareCirclePackingSVG" width="480" height="480"></svg>
    <script type="text/javascript" src="{% static 'myRDB/js/circle_packing/compareCirclePacking.js' %}"></script>
</div>
<div class="card-footer">
    <p>Berechtigungen mit Rechtsklick & Bestätigung<br>zu Nutzerberechtigungen kopieren!</p>
</div>

myRDB_Project/myRDB_app/templates/myRDB/compare/compareProfileTableTemplate.html
<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <tr>
            <th scope="col">TF</th>
            <th scope="col">GF</th>
            <th scope="col">AF</th>
            <th scope="col">Rolle</th>
        </tr>
        {% for row in table_data %}
        <tr>
            <td>{{ row.0}}</td>
            <td>{{ row.1 }}</td>
            <td>{{ row.2 }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.previous_page_number }}&compare_page={{ compareUser_table_data.number }}&view_mode=Tabellarische Ansicht">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?userSearch={{ compareUser.identity }}&page={{ i }}&compare_page={{ compareUser_table_data.number }}&view_mode=Tabellarische Ansicht">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.next_page_number }}&compare_page={{ compareUser_table_data.number }}&view_mode=Tabellarische Ansicht">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

myRDB_Project/myRDB_app/templates/myRDB/compare/compareTableTemplate.html
{% load static %}
<div class="card-header">
    <h5>Vergleichsliste</h5>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table id="compare_data_table" class="table table-hover table-bordered">
        <thead>
            <tr>
                <th scope="col">TF</th>
                <th scope="col">GF</th>
                <th scope="col">AF</th>
                {# <th scope="col">Rolle</th> #}
            </tr>
        </thead>
        <tbody>
            {% for row in compareUser_table_data %}
                <tr>
                    <td>{{ row.0 }}</td>
                    <td>{{ row.1 }}</td>
                    <td>{{ row.2 }}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
        <script type="text/javascript">
            var user_pk = {{ user.pk }};
            var CSRF_TOKEN = "{{ csrf_token }}";
            var compare_data_table;
        </script>
        <script type="text/javascript" src="{% static 'myRDB/js/data_tables/compare_data_table.js' %}"></script>
    </div>
</div>
<div class="card-footer">
</div>


<!--
{% if is_paginated %}
<ul class="pagination">
    {% if compareUser_table_data.has_previous %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ compareUser_table_data.previous_page_number }}&view_mode=Tabellarische Ansicht">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in compareUser_table_data.paginator.page_range %}
    {% if compareUser_table_data.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ i }}&view_mode=Tabellarische Ansicht">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if compareUser_table_data.has_next %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ compareUser_table_data.next_page_number }}&view_mode=Tabellarische Ansicht">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}
-->

myRDB_Project/myRDB_app/templates/myRDB/compare/compare_footer_row.html
<div class="row top-buffer">
    <div class="col">
        {# Hier die Trash-Drop-Fläche realisieren #}
        {% if view_mode == "Graphische Ansicht" %}
            {% include 'myRDB/trashTemplate.html' %}
        {% else %}
            {% include 'myRDB/trashTableTemplate.html' %}
        {% endif %}
    </div>
    <div class="col-6">
        <div class="card">
            {# Hier die Übertragenen-liste realisieren #}
            {% if view_mode == "Graphische Ansicht" %}
                {% include 'myRDB/transferTemplate.html' %}
            {% else %}
                {% include 'myRDB/transferTableTemplate.html' %}
            {% endif %}
        </div>
    </div>
    <div class="col">
        <div class="row-fluid">
            <div class="card">
                <div class="card-body">
                    {# Hier die legende realisieren #}
                </div>
            </div>
        </div>
        <div class="row-fluid top-buffer">
            <div class="card">
                <div class="card-body">
                    {# Hier die verschiedenen Buttons realisieren #}
                     <form id=”apply_changes” method=”POST” action="{% url 'myRDB:apply_changes' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light">Änderungen beantragen</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

myRDB_Project/myRDB_app/templates/myRDB/compare/compare_profile_head.html
<div class="card top-buffer">
    <div class="card-body">
        <div class="row">
            <div class="col-2">
                <img class="card-img-top" src="/../../static/myRDB/images/default_profile.png"
                     alt="Profile Picture">
            </div>
            <div class="col-9">

                <h5 class="card-title">{{ compareUser.identity }}</h5>
                <p class="card-text">{{ compareUser.name }}</p>
                <p class="card-text">{{ compareUser.first_name }}</p>
                <p class="card-text">{{ compareUser.departement_id }}</p>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-sm">
                    <div class="row">
                        <label for="comp_user_count">User:   </label>
                        <p id="comp_user_count" class="card-text">   ...</p>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="row">
                        <label for="comp_role_count">Roles:   </label>
                        <p id="comp_role_count" class="card-text">   {{ comp_role_count }}</p>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="row">
                        <label for="comp_af_count">AF:   </label>
                        <p id="comp_af_count" class="card-text">   {{ comp_af_count }}</p>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="row">
                        <label for="comp_gf_count">GF:   </label>
                        <p id="comp_gf_count" class="card-text">   {{ comp_gf_count }}</p>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="row">
                        <label for="comp_tf_count">TF:   </label>
                        <p id="comp_tf_count" class="card-text">   {{ comp_tf_count }}</p>
                    </div>
                </div>
        </div>
    </div>
</div>