myRDB_Project/myRDB_Project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from myRDB_app import views

from . import settings

'''
    sets REST-API urls
'''
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, 'user')
router.register(r'roles', views.RoleViewSet, 'role')
router.register(r'afs', views.AFViewSet, 'af')
router.register(r'gfs', views.GFViewSet, 'gf')
router.register(r'tfs', views.TFViewSet, 'tf')
router.register(r'orgas', views.OrgaViewSet, 'orga')
router.register(r'groups', views.GroupViewSet, 'group')
router.register(r'departments', views.DepartmentViewSet, ' department')
router.register(r'zi_organisations', views.ZI_OrganisationViewSet, 'zi_organisation')
router.register(r'tf_applications', views.TF_ApplicationViewSet, 'tf_application')
router.register(r'usermodelrights', views.UserModelRightsViewSet, 'usermodelrights')
router.register(r'userlistings', views.UserListingViewSet, 'userlisting')
router.register(r'searchlistings', views.CompleteUserListingViewSet, 'searchlisting')
router.register(r'changerequests', views.ChangeRequestsViewSet, 'changerequests')

urlpatterns = [
    url(r'^', include(router.urls)),
    path('', include('django.contrib.auth.urls')),
    path('myRDB/', include('myRDB_app.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myRDB_Project/myRDB_app/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required,permission_required

from . import views

app_name = 'myRDB'
'''
    sets App urls
'''
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_reset/', views.Password_Reset.as_view(), name='password_reset'),
    path('register/', views.Register.as_view(), name='register'),
    path('profile/', login_required(views.Profile.as_view()), name='profile'),
    path('profile/rights_analysis', login_required(views.ProfileRightsAnalysis.as_view()), name='profile_rights_analysis'),
    path('profile/compare/', login_required(views.Compare.as_view()), name='compare'),
    path('csvToMongo/', permission_required('user.is_staff')(views.CSVtoMongoDB.as_view()), name='csvToMongo'),
    path('users/', permission_required('user.is_staff')(views.Users.as_view()), name='users'),
    path('search_all/', permission_required('user.is_staff')(views.Search_All.as_view()), name='search_all'),
    path('request_pool/', permission_required('user.is_staff')(views.RequestPool.as_view()), name='request_pool'),
    path('my_requests/', login_required(views.MyRequests.as_view()), name='my_requests'),
    path('profile/compare/apply_changes/', login_required(views.RightApplication.as_view()), name='apply_changes'),
]

myRDB_Project/myRDB_app/views.py
import csv
import json
import re

import requests
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import datetime

from django.http import HttpResponseRedirect
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .forms import CustomUserCreationForm, SomeForm, ApplyRightForm, DeleteRightForm, AcceptChangeForm, \
    DeclineChangeForm, CustomAuthenticationForm, ProfileHeaderForm
from .models import Role, AF, GF, TF, Orga, Group, Department, ZI_Organisation, TF_Application, User_AF, User_TF, \
    User_GF, ChangeRequests
from rest_framework import viewsets, status
from .serializers import UserSerializer, RoleSerializer, AFSerializer, GFSerializer, TFSerializer, OrgaSerializer, \
    GroupSerializer, DepartmentSerializer, ZI_OrganisationSerializer, TF_ApplicationSerializer, UserListingSerializer, \
    CompleteUserListingSerializer, UserModelRightsSerializer, ChangeRequestsSerializer
from django.views import generic

from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordResetDoneView

User = get_user_model()
docker_container_ip = "http://148.100.245.159:8000"
#proxies = {'http':"http://172.17.0.3:8000"}
#docker_container_ip = "http://0.0.0.0:8000"
#docker_container_ip = "http://127.0.0.1:8000"


class CSVtoMongoDB(generic.FormView):
    '''
        dataimport-view: reads IIQ-csv (currently hardcoded) line by line and populates Database
            1 line equals 1 user-right
            creates user-profiles to be available for activation by signing-up user
            if element deosnt exist -> create and add reference to user model
            else add reference to user model
    '''
    template_name = 'myRDB/csvToMongo.html'
    form_class = SomeForm
    success_url = '#'

    def form_valid(self, form):
        self.start_import_action()
        return super().form_valid(form)

    def start_import_action(self):
        firstline = True
        # TODO: dateiimportfield und pfad müssen noch verbunden werden!
        #
        with open("myRDB_app/static/myRDB/data/Aus IIQ - User und TF komplett Neu_20180817_abMe.csv",
                  encoding='utf-8') as csvfile:
            csvreader = csv.reader(csvfile, delimiter=';', quotechar='"')
            cur_val = 0
            for line in csvreader:
                line = [re.sub(r'\s+', '', e) for e in line]

                if firstline == True:
                    firstline = False
                    pass
                else:
                    print(line)
                    orga = None
                    try:
                        orga = Orga.objects.get(team=line[8])
                    except(KeyError, Orga.DoesNotExist):
                        orga = Orga(team=line[8])
                    orga.save()

                    tf_application = None
                    try:
                        tf_application = TF_Application.objects.get(application_name=line[9])
                    except(KeyError, TF_Application.DoesNotExist):
                        right_color = "hsl(%d, 50%%, 50%%)" % cur_val
                        tf_application = TF_Application(application_name=line[9], color=right_color)
                        cur_val = (cur_val + 20) % 355

                    tf_application.save()

                    tf = None
                    try:
                        tf = TF.objects.get(tf_name=line[3])
                    except(KeyError, TF.DoesNotExist):
                        tf = TF(tf_name=line[3], tf_description=line[4], highest_criticality_in_AF=line[7],
                                tf_owner_orga=orga, tf_application=tf_application, criticality=line[10])
                    tf.save()

                    gf = None
                    try:
                        gf = GF.objects.get(gf_name=line[11])
                    except(KeyError, GF.DoesNotExist):
                        gf = GF(gf_name=line[11], gf_description=line[12])
                        gf.save()
                    gf.tfs.add(tf)
                    gf.save()

                    af = None
                    try:
                        af = AF.objects.get(af_name=line[5])
                    except(KeyError, AF.DoesNotExist):
                        af = AF(af_name=line[5], af_description=line[6])

                    af.save()
                    af.gfs.add(gf)

                    user = None
                    try:
                        user = User.objects.get(identity=line[0])
                        if user.name != line[1]:
                            user.name = line[1]
                        if user.first_name != line[2]:
                            user.first_name = line[2]
                        if user.username != line[0]:
                            user.username = line[0]
                    except(KeyError, User.DoesNotExist):
                        user = User(identity=line[0], name=line[1], first_name=line[2], username=line[0])
                        if not user.orga:
                            user.orga = Orga()
                        if not user.group:
                            user.group = Group()
                        if not user.department:
                            user.department = Department()
                        if not user.zi_organisation:
                            user.zi_organisation = ZI_Organisation()
                        if not user.roles:
                            user.roles = [Role()]
                        if not user.direct_connect_afs:
                            user.direct_connect_afs = [AF()]
                        if not user.direct_connect_gfs:
                            user.direct_connect_gfs = [GF()]
                        if not user.direct_connect_tfs:
                            user.direct_connect_tfs = [TF()]
                        if not user.my_requests:
                            user.my_requests = [ChangeRequests()]
                        if not user.user_afs:
                            user.user_afs = []
                        if not user.transfer_list:
                            user.transfer_list = []
                        if not user.delete_list:
                            user.delete_list = []
                    if user.user_afs.__len__() == 0:
                        user_tf = User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk, color=tf_application.color)
                        user_gf = User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk, tfs=[])
                        user_af = self.create_user_af(line, af)
                        user_gf.tfs.append(user_tf)
                        user_af.gfs.append(user_gf)
                        user.user_afs.append(user_af)
                    else:
                        afcount = 0
                        for uaf in user.user_afs:
                            if uaf.af_name != af.af_name:
                                afcount += 1
                            else:
                                gfcount = 0
                                for ugf in uaf.gfs:
                                    if ugf.gf_name != gf.gf_name:
                                        gfcount += 1
                                    else:
                                        tfcount = 0
                                        for utf in ugf.tfs:
                                            if utf.tf_name != tf.tf_name:
                                                tfcount += 1
                                            else:
                                                break
                                        if tfcount == ugf.tfs.__len__():
                                            ugf.tfs.append(User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                   color=tf_application.color))
                                if gfcount == uaf.gfs.__len__():
                                    uaf.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                           tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                        color=tf_application.color)]))
                        if afcount == user.user_afs.__len__():
                            user_af = self.create_user_af(line, af)
                            user_af.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                       tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                    color=tf_application.color)]))
                            user.user_afs.append(user_af)

                    user.direct_connect_afs.add(af)
                    user.save()

    def create_user_af(self, line, af):
        if line[15] == "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[])
        if line[15] != "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()
                              , af_valid_till=datetime.datetime.strptime(line[16], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] != "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()

myRDB_Project/myRDB_app/templates/myRDB/rightApplication/right_application.html
{% extends 'myRDB/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    {% include 'myRDB/profile/profile_head.html' %}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-2">
                    <form action="{% url 'myRDB:compare' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light btn-outline-secondary "><--</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <form class="apply-changes-form form-horizontal" action= "{% url 'myRDB:my_requests' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="requesting_user" value="{{ requesting_user }}">
    <input type="hidden" name="compare_user" value="{{ compare_user }}">
        <div id="accordion">
            <div class="card">
                <div class="card-header" id="rightApplicationHeading">
                    <h5 class="mb-0">
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#rightApplication" aria-expanded="true" aria-controls="rightApplication">
                            Beantragung
                        </button>
                    </h5>
                </div>
                <div id="rightApplication" class="collapse show" aria-labelledby="rightApplicationHeading" data-parent="#accordion">
                    <div class="card-body">
                        <div id="inner_accordion_application">
                            {% for right in stripped_transfer_list %}
                                <div class="card">
                                    <div class="card-header" id="inner_rightApplicationHeading{{ forloop.counter0 }}">
                                        <h5 class="mb-0">
                                            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#inner_rightApplication{{ forloop.counter0 }}" aria-expanded="true" aria-controls="inner_rightApplication{{ forloop.counter0 }}">
                                                {{ right.name }}
                                            </button>
                                        </h5>
                                    </div>
                                    {% if forloop.counter0 == 0 %}
                                        <div id="inner_rightApplication{{ forloop.counter0 }}" class="collapse show" aria-labelledby="inner_rightApplicationHeading{{ forloop.counter0 }}" data-parent="#inner_accordion_application">
                                            {% include 'myRDB/rightApplication/right_application_card.html' %}
                                        </div>
                                    {% else %}
                                        <div id="inner_rightApplication{{ forloop.counter0 }}" class="collapse" aria-labelledby="inner_rightApplicationHeading{{ forloop.counter0 }}" data-parent="#inner_accordion_application">
                                            {% include 'myRDB/rightApplication/right_application_card.html' %}
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="rightDeletionHeading">
                    <h5 class="mb-0">
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#rightDeletion" aria-expanded="true" aria-controls="rightDeletion">
                            Löschung
                        </button>
                    </h5>
                </div>
                <div id="rightDeletion" class="collapse" aria-labelledby="rightDeletionHeading" data-parent="#accordion">
                    <div class="card-body">
                        <div id="inner_accordion_deletion">
                            {% for right in stripped_delete_list %}
                                <div class="card">
                                    <div class="card-header" id="inner_rightDeletionHeading{{ forloop.counter0 }}">
                                        <h5 class="mb-0">
                                            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#inner_rightDeletion{{ forloop.counter0 }}" aria-expanded="true" aria-controls="inner_rightDeletion{{ forloop.counter0 }}">
                                                {{ right.name }}
                                            </button>
                                        </h5>
                                    </div>
                                    {% if forloop.counter0 == 0 %}
                                        <div id="inner_rightDeletion{{ forloop.counter0 }}" class="collapse show" aria-labelledby="inner_rightDeletionHeading{{ forloop.counter0 }}" data-parent="#inner_accordion_deletion">
                                            {% include 'myRDB/rightApplication/right_deletion_card.html' %}
                                        </div>
                                    {% else %}
                                        <div id="inner_rightDeletion{{ forloop.counter0 }}" class="collapse" aria-labelledby="inner_rightDeletionHeading{{ forloop.counter0 }}" data-parent="#inner_accordion_deletion">
                                            {% include 'myRDB/rightApplication/right_deletion_card.html' %}
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'myRDB/rightApplication/right_application_footer_row.html' %}
    </form>
    <script type="text/javascript" src="{% static 'myRDB/js/actions/submit_apply_changes.js' %}"></script>
</div>

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/rightApplication/right_application_card.html
{% load static %}
{% load index %}
{% load asjson %}
{% load getdictitem %}
{% load crispy_forms_tags %}

<script type="text/javascript" >var iApplication = 0</script>

<div class="card-body">
    <div class="row">
        <div class="col-4">
            {# hier right-to-delete circle packing #}
            <script type="text/javascript" >
                var jsondata_application{{ forloop.counter0 }} = {{ right | asjson }}
            </script>
            <svg id="rightApplicationSVG{{ forloop.counter0 }}" width="300" height="300"></svg>
            <script type="text/javascript" src="{% static 'myRDB/js/circle_packing/applyChanges/applyChangesCirclePacking_application.js' %}"></script>
        </div>
        <div class="col-8">
            {# hier Formular #}
            <label class="font-weight-bold" for="type">Berechtigungstyp:</label>
            <p class="text-left" id="type">{{ model_transfer_list|index:forloop.counter0|getdictitem:'type'  }}</p>
            <label class="font-weight-bold" for="description">Beschreibung:</label>
            <p class="text-left" id="description">{{ model_transfer_list|index:forloop.counter0|getdictitem:'description'  }}</p>
            <input type="hidden" name="action" value="apply">
            <input type="hidden" name="right_name" value="{{ right.name }}">
            <input type="hidden" name="right_type" value="{{ model_transfer_list|index:forloop.counter0|getdictitem:'type'  }}">
            {{ transfer_form | crispy}}
        </div>
    </div>
</div>

myRDB_Project/myRDB_app/templates/myRDB/rightApplication/right_application_footer_row.html
<div class="row top-buffer">
    <div class="col">
        <div class="card">
            <div class="card-body">
                {# Hier die legende realisieren #}
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                {# Hier die verschiedenen Buttons realisieren #}
                <div class="row">
                    <div class="col">
                        <input type="submit" class="btn btn-light">
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-light">Abbrechen</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

myRDB_Project/myRDB_app/templates/myRDB/rightApplication/right_deletion_card.html
{% load static %}
{% load index %}
{% load asjson %}
{% load getdictitem %}
{% load crispy_forms_tags %}

<script type="text/javascript" >var iDeletion = 0</script>

<div class="card-body">
    <div class="row">
        <div class="col-4">
            {# hier right-to-delete circle packing #}
            <script type="text/javascript" >
                var jsondata_deletion{{ forloop.counter0 }} = {{ right | asjson }}
            </script>
            <svg id="rightDeletionSVG{{ forloop.counter0 }}" width="300" height="300"></svg>
            <script type="text/javascript" src="{% static 'myRDB/js/circle_packing/applyChanges/applyChangesCirclePacking_deletion.js' %}"></script>
        </div>
        <div class="col-8">
            {# hier Formular #}
            <label class="font-weight-bold" for="type">Berechtigungstyp:</label>
            <p class="text-left" id="type">{{ model_delete_list|index:forloop.counter0|getdictitem:'type' }}</p>
            <label class="font-weight-bold" for="description">Beschreibung:</label>
            <p class="text-left" id="description">{{ model_delete_list|index:forloop.counter0|getdictitem:'description' }}</p>
            <input type="hidden" name="action" value="delete">
            <input type="hidden" name="right_name" value="{{ right.name }}">
            <input type="hidden" name="right_type" value="{{ model_delete_list|index:forloop.counter0|getdictitem:'type'  }}">
            {{ delete_form | crispy}}

        </div>
    </div>
</div>