myRDB_Project/myRDB_Project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from myRDB_app import views

from . import settings

'''
    sets REST-API urls
'''
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, 'user')
router.register(r'roles', views.RoleViewSet, 'role')
router.register(r'afs', views.AFViewSet, 'af')
router.register(r'gfs', views.GFViewSet, 'gf')
router.register(r'tfs', views.TFViewSet, 'tf')
router.register(r'orgas', views.OrgaViewSet, 'orga')
router.register(r'groups', views.GroupViewSet, 'group')
router.register(r'departments', views.DepartmentViewSet, ' department')
router.register(r'zi_organisations', views.ZI_OrganisationViewSet, 'zi_organisation')
router.register(r'tf_applications', views.TF_ApplicationViewSet, 'tf_application')
router.register(r'usermodelrights', views.UserModelRightsViewSet, 'usermodelrights')
router.register(r'userlistings', views.UserListingViewSet, 'userlisting')
router.register(r'searchlistings', views.CompleteUserListingViewSet, 'searchlisting')
router.register(r'changerequests', views.ChangeRequestsViewSet, 'changerequests')

urlpatterns = [
    url(r'^', include(router.urls)),
    path('', include('django.contrib.auth.urls')),
    path('myRDB/', include('myRDB_app.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myRDB_Project/myRDB_app/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required,permission_required

from . import views

app_name = 'myRDB'
'''
    sets App urls
'''
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_reset/', views.Password_Reset.as_view(), name='password_reset'),
    path('register/', views.Register.as_view(), name='register'),
    path('profile/', login_required(views.Profile.as_view()), name='profile'),
    path('profile/rights_analysis', login_required(views.ProfileRightsAnalysis.as_view()), name='profile_rights_analysis'),
    path('profile/compare/', login_required(views.Compare.as_view()), name='compare'),
    path('csvToMongo/', permission_required('user.is_staff')(views.CSVtoMongoDB.as_view()), name='csvToMongo'),
    path('users/', permission_required('user.is_staff')(views.Users.as_view()), name='users'),
    path('search_all/', permission_required('user.is_staff')(views.Search_All.as_view()), name='search_all'),
    path('request_pool/', permission_required('user.is_staff')(views.RequestPool.as_view()), name='request_pool'),
    path('my_requests/', login_required(views.MyRequests.as_view()), name='my_requests'),
    path('profile/compare/apply_changes/', login_required(views.RightApplication.as_view()), name='apply_changes'),
]

myRDB_Project/myRDB_app/views.py
import csv
import json
import re

import requests
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import datetime

from django.http import HttpResponseRedirect
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .forms import CustomUserCreationForm, SomeForm, ApplyRightForm, DeleteRightForm, AcceptChangeForm, \
    DeclineChangeForm, CustomAuthenticationForm, ProfileHeaderForm
from .models import Role, AF, GF, TF, Orga, Group, Department, ZI_Organisation, TF_Application, User_AF, User_TF, \
    User_GF, ChangeRequests
from rest_framework import viewsets, status
from .serializers import UserSerializer, RoleSerializer, AFSerializer, GFSerializer, TFSerializer, OrgaSerializer, \
    GroupSerializer, DepartmentSerializer, ZI_OrganisationSerializer, TF_ApplicationSerializer, UserListingSerializer, \
    CompleteUserListingSerializer, UserModelRightsSerializer, ChangeRequestsSerializer
from django.views import generic

from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordResetDoneView

User = get_user_model()
docker_container_ip = "http://148.100.245.159:8000"
#proxies = {'http':"http://172.17.0.3:8000"}
#docker_container_ip = "http://0.0.0.0:8000"
#docker_container_ip = "http://127.0.0.1:8000"


class CSVtoMongoDB(generic.FormView):
    '''
        dataimport-view: reads IIQ-csv (currently hardcoded) line by line and populates Database
            1 line equals 1 user-right
            creates user-profiles to be available for activation by signing-up user
            if element deosnt exist -> create and add reference to user model
            else add reference to user model
    '''
    template_name = 'myRDB/csvToMongo.html'
    form_class = SomeForm
    success_url = '#'

    def form_valid(self, form):
        self.start_import_action()
        return super().form_valid(form)

    def start_import_action(self):
        firstline = True
        # TODO: dateiimportfield und pfad müssen noch verbunden werden!
        #
        with open("myRDB_app/static/myRDB/data/Aus IIQ - User und TF komplett Neu_20180817_abMe.csv",
                  encoding='utf-8') as csvfile:
            csvreader = csv.reader(csvfile, delimiter=';', quotechar='"')
            cur_val = 0
            for line in csvreader:
                line = [re.sub(r'\s+', '', e) for e in line]

                if firstline == True:
                    firstline = False
                    pass
                else:
                    print(line)
                    orga = None
                    try:
                        orga = Orga.objects.get(team=line[8])
                    except(KeyError, Orga.DoesNotExist):
                        orga = Orga(team=line[8])
                    orga.save()

                    tf_application = None
                    try:
                        tf_application = TF_Application.objects.get(application_name=line[9])
                    except(KeyError, TF_Application.DoesNotExist):
                        right_color = "hsl(%d, 50%%, 50%%)" % cur_val
                        tf_application = TF_Application(application_name=line[9], color=right_color)
                        cur_val = (cur_val + 20) % 355

                    tf_application.save()

                    tf = None
                    try:
                        tf = TF.objects.get(tf_name=line[3])
                    except(KeyError, TF.DoesNotExist):
                        tf = TF(tf_name=line[3], tf_description=line[4], highest_criticality_in_AF=line[7],
                                tf_owner_orga=orga, tf_application=tf_application, criticality=line[10])
                    tf.save()

                    gf = None
                    try:
                        gf = GF.objects.get(gf_name=line[11])
                    except(KeyError, GF.DoesNotExist):
                        gf = GF(gf_name=line[11], gf_description=line[12])
                        gf.save()
                    gf.tfs.add(tf)
                    gf.save()

                    af = None
                    try:
                        af = AF.objects.get(af_name=line[5])
                    except(KeyError, AF.DoesNotExist):
                        af = AF(af_name=line[5], af_description=line[6])

                    af.save()
                    af.gfs.add(gf)

                    user = None
                    try:
                        user = User.objects.get(identity=line[0])
                        if user.name != line[1]:
                            user.name = line[1]
                        if user.first_name != line[2]:
                            user.first_name = line[2]
                        if user.username != line[0]:
                            user.username = line[0]
                    except(KeyError, User.DoesNotExist):
                        user = User(identity=line[0], name=line[1], first_name=line[2], username=line[0])
                        if not user.orga:
                            user.orga = Orga()
                        if not user.group:
                            user.group = Group()
                        if not user.department:
                            user.department = Department()
                        if not user.zi_organisation:
                            user.zi_organisation = ZI_Organisation()
                        if not user.roles:
                            user.roles = [Role()]
                        if not user.direct_connect_afs:
                            user.direct_connect_afs = [AF()]
                        if not user.direct_connect_gfs:
                            user.direct_connect_gfs = [GF()]
                        if not user.direct_connect_tfs:
                            user.direct_connect_tfs = [TF()]
                        if not user.my_requests:
                            user.my_requests = [ChangeRequests()]
                        if not user.user_afs:
                            user.user_afs = []
                        if not user.transfer_list:
                            user.transfer_list = []
                        if not user.delete_list:
                            user.delete_list = []
                    if user.user_afs.__len__() == 0:
                        user_tf = User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk, color=tf_application.color)
                        user_gf = User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk, tfs=[])
                        user_af = self.create_user_af(line, af)
                        user_gf.tfs.append(user_tf)
                        user_af.gfs.append(user_gf)
                        user.user_afs.append(user_af)
                    else:
                        afcount = 0
                        for uaf in user.user_afs:
                            if uaf.af_name != af.af_name:
                                afcount += 1
                            else:
                                gfcount = 0
                                for ugf in uaf.gfs:
                                    if ugf.gf_name != gf.gf_name:
                                        gfcount += 1
                                    else:
                                        tfcount = 0
                                        for utf in ugf.tfs:
                                            if utf.tf_name != tf.tf_name:
                                                tfcount += 1
                                            else:
                                                break
                                        if tfcount == ugf.tfs.__len__():
                                            ugf.tfs.append(User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                   color=tf_application.color))
                                if gfcount == uaf.gfs.__len__():
                                    uaf.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                           tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                        color=tf_application.color)]))
                        if afcount == user.user_afs.__len__():
                            user_af = self.create_user_af(line, af)
                            user_af.gfs.append(User_GF(gf_name=gf.gf_name, model_gf_pk=gf.pk,
                                                       tfs=[User_TF(tf_name=tf.tf_name, model_tf_pk=tf.pk,
                                                                    color=tf_application.color)]))
                            user.user_afs.append(user_af)

                    user.direct_connect_afs.add(af)
                    user.save()

    def create_user_af(self, line, af):
        if line[15] == "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[])
        if line[15] != "" and line[16] == "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] == "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()
                              , af_valid_till=datetime.datetime.strptime(line[16], "%d.%m.%Y").isoformat())
        if line[15] != "" and line[16] != "" and line[17] != "":
            user_af = User_AF(af_name=af.af_name, model_af_pk=af.pk, gfs=[]
                              , af_valid_from=datetime.datetime.strptime(line[15], "%d.%m.%Y").isoformat()

myRDB_Project/myRDB_app/templates/myRDB/compare.html
{% extends 'myRDB/base.html' %}
{% block content %}
<div class="row top-buffer">
    <div class="col-6" id="user_card">
        {% include 'myRDB/profile_head.html' %}
        <div class="card top-buffer">
            <div class="card-body">
                {% if view_mode == "Graphische Ansicht" %}
                    {% include 'myRDB/circlePackingTemplate.html' %}
                {% else %}
                    {% include 'myRDB/profileTableTemplate.html' %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-6">
        {% include 'myRDB/compare_profile_head.html' %}
        <div class="card top-buffer">
            <div class="card-body">
                {% if view_mode == "Graphische Ansicht" %}
                    {% include 'myRDB/compareCirclePackingTemplate.html' %}
                {% else %}
                    {% include 'myRDB/compareTableTemplate.html' %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row-fluid top-buffer">
    {# hier umschalt button auf tabellarische/visuelle ansicht #}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-2">
                    <label for="viewMode">Ansicht: </label>
                </div>
                <div class="col-3">
                    <form>
                        {% csrf_token %}
                        <input name="user_identity" type="hidden" value="{{ user_identity }}">
                        <input name="userSearch" type="hidden" value="{{ compareUser.identity }}">
                        <select id="viewMode" name="view_mode" class="form-control" onchange="form.submit()">
                            {% if view_mode == "Graphische Ansicht"%}
                                <option selected>Graphische Ansicht</option>
                                <option>Tabellarische Ansicht</option>
                            {% else %}
                                <option>Graphische Ansicht</option>
                                <option selected>Tabellarische Ansicht</option>
                            {% endif %}
                        </select>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'myRDB/compare_footer_row.html' %}

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/compareProfileTableTemplate.html
<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <tr>
            <th scope="col">TF</th>
            <th scope="col">GF</th>
            <th scope="col">AF</th>
            <th scope="col">Rolle</th>
        </tr>
        {% for row in table_data %}
        <tr>
            <td>{{ row.0}}</td>
            <td>{{ row.1 }}</td>
            <td>{{ row.2 }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.previous_page_number }}&compare_page={{ compareUser_table_data.number }}">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?userSearch={{ compareUser.identity }}&page={{ i }}&compare_page={{ compareUser_table_data.number }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.next_page_number }}&compare_page={{ compareUser_table_data.number }}">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

myRDB_Project/myRDB_app/templates/myRDB/index.html
{% extends 'myRDB/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>Wilkommen in der RechteDB</h1>
{% if user.is_authenticated %}
Hi {{user.identity}} !
<p><a href="{% url 'myRDB:logout' %}">logout</a></p>
{% else %}
<p>You are not logged in!</p>
<a href="{% url 'myRDB:login' %}">login</a>
<a href="{% url 'myRDB:register' %}">sign up</a>
{% endif %}

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/navbar.html
{% extends 'myRDB/base.html' %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
            <li><a class="nav-item nav-link" href="{% url 'myRDB:profile' %}">Profile</a></li>
            <li><a class="nav-item nav-link" href="{% url 'myRDB:csvToMongo' %}">CSVintoMongoDB</a></li>
            <li><a class="nav-item nav-link disabled" href="#">Disabled</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><p>Youre logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:logout' %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li><p>Youre not logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:login' %}">Login<span
                    class="sr-only">(current)</span></a></li>
            {% endif %}

        </ul>
    </div>
</nav>

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/profile.html
{% extends 'myRDB/base.html' %}
{% block content %}
<div class="container-fluid">
    {% include 'myRDB/profile_head.html' %}

        <div class="row top-buffer">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% if view_mode == "Graphische Ansicht" %}
                            {% include 'myRDB/circlePackingTemplate.html' %}
                        {% else %}
                            {% include 'myRDB/profileTableTemplate.html' %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="row">
                    <div class="col">
                        {% include 'myRDB/scatterPlotTemplate.html' %}
                    </div>
                </div>
                <div class="row top-buffer">
                    <div class="col">
                        {% include 'myRDB/trashTemplate.html' %}
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                {# Hier die verschiedenen Buttons realisieren #}
                                <div class="row">
                                    <div class="col">
                                        <form id=”log” method=”POST” action="{% url 'myRDB:compare' %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-light">Logdatei anzeigen</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="row top-buffer">
                                    <div class="col">
                                        <form id=”analysis” method=”POST” action="{% url 'myRDB:profile_rights_analysis' %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-light">Berechtigungsanalyse</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="row top-buffer">
                                    <div class="col">
                                        <button type="button" class="btn btn-light">Rechte Beantragen</button>
                                    </div>
                                </div>
                                <div class="row top-buffer">
                                    <div class="col">
                                        <button type="button" class="btn btn-light">Löschung beantragen</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid top-buffer">
    {# hier umschalt button auf tabellarische/visuelle ansicht #}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <label for="viewMode">Ansicht: </label>
                        </div>
                        <div class="col-3">
                            <form>
                                {% csrf_token %}
                                {% if identity_param %}
                                    <input name="identity" type="hidden" value="{{ identity_param }}">
                                {% endif %}
                                <select id="viewMode" name="view_mode" class="form-control" onchange="form.submit()">
                                    {% if view_mode == "Graphische Ansicht"%}
                                        <option selected>Graphische Ansicht</option>
                                        <option>Tabellarische Ansicht</option>
                                    {% else %}
                                        <option>Graphische Ansicht</option>
                                        <option selected>Tabellarische Ansicht</option>
                                    {% endif %}
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>

<script>
        $(document).ready(function(){
            $("#txtSearch").autocomplete({
                source: "/ajax_calls/search/",
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });

        });



</script>

{% endblock %}

myRDB_Project/myRDB_app/templates/myRDB/users.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>Users</h1>
<form id=”search” method=”POST” action="{% url 'myRDB:users' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="search">Suchkategorie:</label>
                        <select class="form-control" id="search" name="search_what">
                            {% if search_what == "identity" %}
                                <option value="identity" selected>XVNummer</option>
                            {% else %}
                                <option value="identity">XVNummer</option>
                            {% endif %}
                            {% if search_what == "name" %}
                                <option value="name" selected>Name</option>
                            {% else %}
                                <option value="name">Name</option>
                            {%  endif %}
                            {% if search_what == "first_name" %}
                                <option value="first_name" selected>Vorname</option>
                            {% else %}
                                <option value="first_name">Vorname</option>
                            {% endif %}
                        </select>
                    </div>
                    <div class="col">
                        <label for="txtSearch">Suchfeld:</label>
                        <input class="form-control" type="text" id=”txtSearch” name='userSearch' value="{{ userSearch }}"
                               placeholder="beginnt mit...">
                    </div>
                </div>
            </div>
        </div>
        {% if zi_organisations %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <label for="zi_organisation">ZI-Organisation:</label>
                <select class="form-control" name="zi_organisation" id="zi_organisation">
                    <option>----</option>
                    {% for e in zi_organisations %}
                        {% if e.team == zi_organisation %}
                            <option selected>{{ e.zi_organisation_name }}</option>
                        {% else %}
                            <option>{{ e.zi_organisation_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        {% if departments %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <label for="department">Abteilung:</label>
                <select class="form-control" name="department" id="department">
                    <option>----</option>
                    {% for e in departments %}
                        {% if e.team == department %}
                            <option selected>{{ e.department_name }}</option>
                        {% else %}
                            <option>{{ e.department_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        {% if orgas %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <label for="orga">Team:</label>
                <select class="form-control" name="orga" id="orga">
                    <option>----</option>
                    {% for e in orgas %}
                        {% if e.team == orga %}
                            <option selected>{{ e.team }}</option>
                        {% else %}
                            <option>{{ e.team }}</option>
                        {% endif %}

                    {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        {% if groups %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <label for="role">Rolle:</label>
                <select class="form-control" name="role" id="role">
                    <option>----</option>
                    {% for e in groups %}
                        {% if e.team == group %}
                            <option selected>{{ e.group_name }}</option>
                        {% else %}
                            <option>{{ e.group_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        {% if roles %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <label for="role">Rolle:</label>
                <select class="form-control" name="role" id="role">
                    <option>----</option>
                    {% for e in roles %}
                        {% if e.team == role %}
                            <option selected>{{ e.role_name }}</option>
                        {% else %}
                            <option>{{ e.role_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        {% endif %}
        <div class="col-6 col-sm-4 col-md col-lg col-xl">
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="entries_per_page">Zeilen pro Seite:</label>
                        <input class="form-control" type="text" id=”entries_per_page” name='entries_per_page' value="{{ paged_data.paginator.per_page }}"
                               placeholder="... Zeilen">
                    </div>
                    <div class="col">
                        <div class="row">
                            <label class="hidden">Suchen:</label>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-light btn-outline-secondary " id="sub-button">Suche</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<ul>
    {% for user in object_list %}
    <li>
        <div class="row">
            <div class="col-4 col-sm-2 col-md-2 col-lg-1 col-xl-1">
                <a href="{% url 'myRDB:profile' %}?identity={{ user.identity }}" class="badge badge-info"> {{ user.identity }}</a>
            </div>
            <div class="col-6">
                <p>{{ user.name }}, {{ user.first_name }} </p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% if is_paginated %}
<ul class="pagination">
    {% if paged_data.has_previous %}
    <li><a href="{{ params_for_pagination }}&page={{ paged_data.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paged_data.paginator.page_range %}
    {% if paged_data.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="{{ params_for_pagination }}&page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if paged_data.has_next %}
    <li><a href="{{ params_for_pagination }}&page={{ paged_data.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}